server:
  port: 3033

spring:
  datasource:
    username: ${zeus.postgresql.username}
    password: ${zeus.postgresql.password}
    url: ${zeus.postgresql.url}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: zeus-user
  cloud:
      nacos:
        discovery:
          server-addr: resource.leons-tokyo.top:8848
          username: ${zeus.nacos.username}
          password: ${zeus.nacos.password}
          group: zeus
